package ai.cliff.assessment.model;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

@Data
@Entity //declaring as entity
@Table(name="teams")//declaring table name
public class Team {

	@Id //declaring teamid as primary key
	@GeneratedValue
	@JsonFormat(shape = JsonFormat.Shape.NUMBER)
	private int teamid;//made teamid as primary key for teams table which will be autogenerated value
	//formating name and location
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String teamname;
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String teamlocation;
	
	//formating date format for createdat and updatedat columns
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
	private Date createdat;
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
	private Date updatedat;
	
	//for one to many mapping
	@JsonFormat(shape = JsonFormat.Shape.ARRAY)
	@OneToMany(targetEntity = Player.class,cascade = CascadeType.ALL)
	@JoinColumn(name = "teamid_fk", referencedColumnName = "teamid")
	private List<Player> players;
	
	//generating getters and setters
	public int getTeamid() {
		return teamid;
	}
	public void setTeamid(int teamid) {
		this.teamid = teamid;
	}
	public String getTeamname() {
		return teamname;
	}
	public void setTeamname(String teamname) {
		this.teamname = teamname;
	}
	public String getTeamlocation() {
		return teamlocation;
	}
	public void setTeamlocation(String teamlocation) {
		this.teamlocation = teamlocation;
	}
	public Date getCreatedat() {
		return createdat;
	}
	public void setCreatedat(Date createdat) {
		this.createdat = createdat;
	}
	public Date getUpdatedat() {
		return updatedat;
	}
	public void setUpdatedat(Date updatedat) {
		this.updatedat = updatedat;
	}
	
	
}
